blueprint:
  name: DeHumidifier Automations
  description: Turn off/on dehumidifier based on humidity sensor
  source_url: https://github.com/TheRealWaldo/ha-blueprints/blob/main/blueprints/automation/TheRealWaldo/dehumidifier.yaml
  domain: automation
  input:

    current_humidity_sensor:
      name: Humidity Sensor
      description: The sensor to read the current humidity from
      selector:
        entity:
          domain: sensor
          device_class: humidity

    optimal_humidity_sensor:
      name: Optimal Humidity Sensor
      description: The sensor to get the humidity setpoint from
      selector:
        entity:
          domain: sensor
          device_class: humidity

    only_on_mold_warning:
      name: Only dehumidify on mold warning?
      description: Requires an optimal humidity sensor with a mold_warning attribute as a boolean.
      default: false
      selector:
        boolean:

    disable_delay:
      name: Off Delay
      description: Delay (in minutes) before turning off dehumidification
      default: 1
      selector:
        number:
          min: 0
          max: 30
          step: 1
          mode: slider

    dehumidifier_switches:
      name: De-humidifier Switches
      description: Switches to turn on when we call for dehumidification
      selector:
        target:
          entity:
            domain: switch

    opposing_switches:
      name: Opposing Switches
      description: Switches to turn off when we call for dehumidification
      default: {}
      selector:
        target:
          entity:
            domain: switch

variables:
  opposing_switches: !input opposing_switches
  only_on_mold_warning: !input only_on_mold_warning

mode: queued
max_exceeded: silent

trigger:
  - platform: numeric_state
    id: "above_optimal"
    entity_id: !input current_humidity_sensor
    above: !input optimal_humidity_sensor

  - platform: numeric_state
    id: "below_optimal"
    entity_id: !input current_humidity_sensor
    below: !input optimal_humidity_sensor
    for:
      minutes: !input disable_delay

  - platform: state
    id: "mold_warning"
    entity_id: !input optimal_humidity_sensor
    attribute: mold_warning
    from: false
    to: true

  - platform: state
    id: "mold_warning_ended"
    entity_id: !input optimal_humidity_sensor
    attribute: mold_warning
    to: false
    for:
      minutes: !input disable_delay

action:
  - choose:

    - conditions:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: "above_optimal"
              - "{{ not only_on_mold_warning }}"
          - condition: trigger
            id: "mold_warning"

      sequence:

        - alias: Turn on dehumidifiers
          service: switch.turn_on
          target: !input dehumidifier_switches

        - alias: Check if opposing switches are enabled
          condition: template
          value_template: "{{ opposing_switches != {} }}"

        - alias: Turn off opposing_switches
          service: switch.turn_off
          target: !input opposing_switches

    - conditions:
      - condition: or
        conditions:
          - condition: trigger
            id: "below_optimal"
          - condition: trigger
            id: "mold_warning_ended"

      sequence:

      - alias: Turn off dehumidifier
        service: switch.turn_off
        target: !input dehumidifier_switches
