blueprint:
  name: Humidifier Automations
  description: Turn off/on humidifier based on humidity sensor
  source_url: https://github.com/TheRealWaldo/ha-humidifier/blob/main/blueprints/automation/TheRealWaldo/humidifier.yaml
  domain: automation
  input:
    current_humidity_sensor:
      name: Humidity Sensor
      description: The sensor to read the current humidity from
      selector:
        entity:
          domain: sensor
          device_class: humidity
    optimal_humidity_sensor:
      name: Optimal Humidity Sensor
      description: The sensor to get the humidity setpoint from
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hvac:
      name: HVAC System
      description: Avoid running the humidifier if the HVAC system is idle
      selector:
        entity:
          domain: climate
    humidifier_switches:
      name: Humidifier Switches
      description: The switch to turn on when we call for humidification
      selector:
        target:
          entity:
            domain: switch
    opposing_switches:
      name: Opposing Switches
      description: Switches to turn off when we call for humidification
      default: {}
      selector:
        target:
          entity:
            domain: switch

variables:
  optimal_humidity_sensor: !input optimal_humidity_sensor
  current_humidity_sensor: !input current_humidity_sensor
  humidifier_switches: !input humidifier_switches
  opposing_switches: !input opposing_switches

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - !input optimal_humidity_sensor
      - !input current_humidity_sensor
  - platform: state
    entity_id:
      - !input hvac
    attribute: 'hvac_action'
action:
  - choose:
    - conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: !input hvac
            attribute: 'hvac_action'
            state: 'idle'
      - "{{ states(current_humidity_sensor)|float < states(optimal_humidity_sensor)|float }}"

      sequence:
        - alias: Turn on humidifiers
          service: switch.turn_on
          target: !input humidifier_switches

        - alias: Check if opposing switches are enabled
          condition: template
          value_template: "{{ opposing_switches != {} }}"

        - alias: Turn off opposing_switches
          service: switch.turn_off
          target: !input opposing_switches

    default:

      - alias: Turn off humidifiers
        service: switch.turn_off
        target: !input humidifier_switches

      - alias: Check if opposing switches are enabled
        condition: template
        value_template: "{{ opposing_switches != {} }}"

      - alias: Turn off opposing_switches
        service: switch.turn_off
        target: !input opposing_switches
