blueprint:
  name: DeHumidifier Automations
  description: Turn off/on dehumidifier based on humidity sensor
  source_url: https://github.com/TheRealWaldo/ha-humidifier/blob/main/dehumidifier.yaml
  domain: automation
  input:
    current_humidity_sensor:
      name: Humidity Sensor
      description: The sensor to read the current humidity from
      selector:
        entity:
          domain: sensor
          device_class: humidity
    optimal_humidity_sensor:
      name: Optimal Humidity Sensor
      description: The sensor to get the humidity setpoint from
      selector:
        entity:
          domain: sensor
          device_class: humidity
    dehumidifier_trigger_range:
      name: Trigger Range
      description: The difference in humidity to trigger dehumidification
      default: 1
      selector:
        number:
          min: 1
          max: 25
          step: 1
          unit_of_measurement: '%'
          mode: slider
    dehumidifier_switches:
      name: De-humidifier Switches
      description: Switches to turn on when we call for dehumidification
      selector:
        target:
          entity:
            domain: switch
    opposing_switches:
      name: Opposing Switches
      description: Switches to turn off when we call for dehumidification
      default: {}
      selector:
        target:
          entity:
            domain: switch


variables:
  optimal_humidity_sensor: !input optimal_humidity_sensor
  current_humidity_sensor: !input current_humidity_sensor
  dehumidifier_trigger_range: !input dehumidifier_trigger_range
  dehumidifier_switches: !input dehumidifier_switches
  opposing_switches: !input opposing_switches

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - !input optimal_humidity_sensor
      - !input current_humidity_sensor

action:
  - choose:

    - conditions:
      - "{{ states(current_humidity_sensor)|float >= states(optimal_humidity_sensor)|float + dehumidifier_trigger_range }}"

      sequence:
        - alias: Turn on dehumidifiers
          service: switch.turn_on
          target: !input dehumidifier_switches

        - alias: Check if opposing switches are enabled
          condition: template
          value_template: "{{ opposing_switches != {} }}"

        - alias: Turn off opposing_switches
          service: switch.turn_off
          target: !input opposing_switches

    default:
      - alias: Wait 1 minute to avoid bouncing too quickly
        delay:
          minutes: 1

      - alias: Turn off dehumidifier
        service: switch.turn_off
        target: !input dehumidifier_switches

      - alias: Check if opposing switches are enabled
        condition: template
        value_template: "{{ opposing_switches != {} }}"

      - alias: Turn off opposing_switches
        service: switch.turn_off
        target: !input opposing_switches
