
blueprint:
  name: Humidifier Automations
  description: Turn off/on humidifier based on humidity sensor
  domain: automation
  input:
    current_humidity_sensor:
      name: Humidity Sensor
      description: The sensor to read the current humidity from
      selector:
        entity:
          domain: sensor
          device_class: humidity
    optimal_humidity_sensor:
      name: Optimal Humidity Sensor
      description: The sensor to get the humidity setpoint from
      selector:
        entity:
          domain: sensor
          device_class: humidity
    dehumidifier_trigger_range:
      name: Trigger Range
      description: The difference in humidity to trigger dehumidification
      default: 1
      selector:
        number:
          min: 1
          max: 25
          step: 1
          unit_of_measurement: '%'
          mode: slider
    hvac:
      name: HVAC System
      description: Avoid running the humidifier if the HVAC system is idle
      selector:
        entity:
          domain: climate
    humidifier_switch:
      name: Humidifier Switch
      description: The switch to turn on when humidity is needed
      default: {}
      selector:
        target:
          entity:
            domain: switch
    dehumidifier_switch:
      name: De-humidifier Switch
      description: The switch to turn on when humidity is too high
      default: {}
      selector:
        target:
          entity:
            domain: switch

variables:
  optimal_humidity_sensor: !input optimal_humidity_sensor
  current_humidity_sensor: !input current_humidity_sensor
  dehumidifier_trigger_range: !input dehumidifier_trigger_range
  humidifier_switch: !input humidifier_switch
  dehumidifier_switch: !input dehumidifier_switch

trigger:
  - platform: state
    entity_id:
      - !input optimal_humidity_sensor
      - !input current_humidity_sensor
  - platform: state
    entity_id:
      - !input hvac
    attribute: 'hvac_action'
action:
  - choose:
    - conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: !input hvac
            attribute: 'hvac_action'
            state: 'idle'
      - "{{ states(current_humidity_sensor)|float < states(optimal_humidity_sensor)|float }}"
      - "{{ humidifier_switch != none }}"

      sequence:
        - service: switch.turn_on
          target: !input humidifier_switch

    - conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: !input hvac
            attribute: 'hvac_action'
            state: 'idle'
          - "{{ states(current_humidity_sensor)|float >= states(optimal_humidity_sensor)|float }}"
          - "{{ humidifier_switch != none }}"

      sequence:
        - service: switch.turn_off
          target: !input humidifier_switch

    - conditions:
      - "{{ states(current_humidity_sensor)|float >= states(optimal_humidity_sensor)|float + dehumidifier_trigger_range }}"
      - "{{ dehumidifier_switch != none }}"

      sequence:
        - service: switch.turn_on
          target: !input dehumidifier_switch

    - conditions:
      - "{{ states(current_humidity_sensor)|float < states(optimal_humidity_sensor)|float + dehumidifier_trigger_range }}"
      - "{{ dehumidifier_switch != none }}"

      sequence:
        - service: switch.turn_off
          target: !input dehumidifier_switch
